### ISSUE TITLE
Flow deployment failed 

### ISSUE THREAD

**Issue by chimo599** [jina-ai/jcloud#136]
#### Command
```bash
# # jc deploy flow.yml
```

#### Flow yaml
```yaml
# jtype: Flow
version: '1'

gateway:
  protocol: http
  port: 54321
pods:
  - name: index_table_extractor
    uses: jinahub+docker://PDFTableExtractor/latest
    install_requirements: true
  - name: index_segmenter
    uses: jinahub+docker://PDFSegmenter
    install_requirements: true
  - name: index_tagger
    uses: jinahub+docker://ElementTypeTagger
    uses_with:
      traversal_paths: "@c"
  - name: index_sentencizer
    uses: jinahub+docker://SpacySentencizer
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: index_tags_copier
    uses: jinahub+docker://TagsCopier
    uses_with:
      traversal_paths: "@c"
  - name: index_flattener
    uses: jinahub+docker://ChunkFlattener
  - name: index_image_processor
    uses: jinahub+docker://ImagePreprocessor-skip-non-images
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: search_image_processor
    uses: jinahub+docker://ImagePreprocessor-skip-non-images
    uses_with:
      traversal_paths: "@r"
    install_requirements: true
  - name: index_encoder
    uses: jinahub+docker://CLIPEncoder/latest-gpu
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: search_encoder
    uses: jinahub+docker://CLIPEncoder/latest-gpu
    install_requirements: true
  - name: all_indexer
    uses: jinahub+docker://AnnLiteIndexer
    uses_with:
      index_traversal_paths: "@c"
      search_traversal_paths: "@c"
      columns:
        - ["element_type", "str"]
      n_dim: 512
    install_requirements: true

```

#### Flow ID / Request ID
```text
Flow ID: N/A
Request ID: N/A
```

---

#### `jina` version
```bash
jina -vf
jina 3.14.1
...
```

#### Logs

N/A

---

#### Additional context
![1](https://user-images.githubusercontent.com/79641303/225560504-5b602e55-0639-450f-9f73-0cab432611ea.PNG)
![2](https://user-images.githubusercontent.com/79641303/225560492-1514c535-9afb-4b3a-97a1-7325c39e37a2.PNG)
![3](https://user-images.githubusercontent.com/79641303/225560480-82be5eab-c498-4c79-882f-5bdcb3268f80.PNG)

busercontent.com/79641303/225560209-e1f56b21-af8c-4603-b1cd-762dd2b06d08.PNG)

**Comment by npitsillos** [comment]
Hello @chimo599 thank you for the issue. Can I ask you to retry this with the below `flow.yml`
```
jtype: Flow
version: '1'

gateway:
  protocol: [http]
  port: [54321]
executors:
  - name: index_table_extractor
    uses: jinahub+docker://PDFTableExtractor/latest
    install_requirements: true
  - name: index_segmenter
    uses: jinahub+docker://PDFSegmenter
    install_requirements: true
  - name: index_tagger
    uses: jinahub+docker://ElementTypeTagger
    uses_with:
      traversal_paths: "@c"
  - name: index_sentencizer
    uses: jinahub+docker://SpacySentencizer
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: index_tags_copier
    uses: jinahub+docker://TagsCopier
    uses_with:
      traversal_paths: "@c"
  - name: index_flattener
    uses: jinahub+docker://ChunkFlattener
  - name: index_image_processor
    uses: jinahub+docker://ImagePreprocessor-skip-non-images
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: search_image_processor
    uses: jinahub+docker://ImagePreprocessor-skip-non-images
    uses_with:
      traversal_paths: "@r"
    install_requirements: true
  - name: index_encoder
    uses: jinahub+docker://CLIPEncoder/latest-gpu
    uses_with:
      traversal_paths: "@c"
    install_requirements: true
  - name: search_encoder
    uses: jinahub+docker://CLIPEncoder/latest-gpu
    install_requirements: true
  - name: all_indexer
    uses: jinahub+docker://AnnLiteIndexer
    uses_with:
      index_traversal_paths: "@c"
      search_traversal_paths: "@c"
      columns:
        - ["element_type", "str"]
      n_dim: 512
    install_requirements: true
```
