### ISSUE TITLE
Receive Secrets from OS at Runtime for Config

### ISSUE THREAD

**Issue by myntoralex** [jina-ai/jcloud#19]
I use the HNSWPostgresIndexer, with which I provide some database secrets I would like to keep secret. In my python code for my executor I do the following, 

```
...
uses_with={
                'table': 'odqa_encoded_document',
                'limit': 20,
                'dim': 768,
                'return_embeddings': True,
                'hostname': os.environ.get('POSTGRES_HOST'),
                'username': os.environ.get('POSTGRES_USER'),
                'password': os.environ.get('POSTGRES_PASSWORD'),
                'database': os.environ.get('POSTGRES_DB')}
  ...
```
But in my yaml file for running with jcloud deploy, I have those values hardcoded. 

```
uses_with:
    table: odqa_encoded_document
    limit: 20
    dim: 768
    return_embeddings: true
    hostname: SECRET
    username: SECRET
    password: SECRET
    database: SECRET
```

Maybe all I need is a note in the README for externalizing these values.
