### ISSUE TITLE
Issue when loading empty list from environment variables to flow yaml

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/jcloud#81]
Using an empty list as environment variable causes jcloud to not use it as [] but as [None].

This is the same issue jina had: https://github.com/jina-ai/jina/issues/5142.

#### Command
```bash
jc deploy --env-file test.env testFlow.yml
```

#### test.env
```bash
JINA_NOW_ADMIN_EMAILS=[]
```

#### testFlow.yaml
```yaml
jtype: Flow
executors:
  - name: preprocessor
    uses: jinahub+docker://NOWPreprocessor/v0.0.79-auth-exec-4
    uses_with:
      app: text_to_video
      admin_emails: ${{ ENV.JINA_NOW_ADMIN_EMAILS }}
```

<img width="1095" alt="Screenshot 2022-09-08 at 22 23 47" src="https://user-images.githubusercontent.com/47435119/189218707-ac68cba4-f52d-4ce8-a490-020dd10a8f55.png">

---

#### `jina` version
```bash
- jina 3.9.1
- docarray 0.16.3
- jcloud 0.0.35
- jina-hubble-sdk v0.0.0
- jina-proto 0.1.13
- protobuf 3.19.4
- proto-backend cpp
- grpcio 1.46.3
- pyyaml 6.0
- python 3.9.12
- platform Darwin
- platform-release 21.6.0
- platform-version Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 190070690681122
- session-id 9c8367b4-2fb4-11ed-868a-acde48001122
- uptime 2022-09-08T22:27:07.862245
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
```
