### ISSUE TITLE
JCloud breaking changes

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jcloud#88]
## Jina Version
JCloud uses `jina ping` command for readiness checks, which was added in jina `3.10.0`. So it is compatible with any jina version >=3.10.0. 

## Changes to JCloud args

1. [spot vs on-demand](https://docs.jina.ai/fundamentals/jcloud/yaml-spec/#spot-vs-on-demand-instance) moved under `resources`

<table>
<tr>
<td> <center><b>Before</b></center> </td> <td><b><center>After</center></b></td>
</tr>
<tr>
<td>

```yaml
jtype: Flow
executors:
  - name: executor1
    uses: jinahub+docker://Executor1
    jcloud:
      capacity: on-demand
```
</td>
<td>

```yaml
jtype: Flow
executors:
  - name: executor1
    uses: jinahub+docker://Executor1
    jcloud:
      resources:
        capacity: on-demand
```
</td>
</tr>
</table>

2. [expose_gateway](https://docs.jina.ai/fundamentals/jcloud/yaml-spec/#disable-gateway) is renamed to `expose`. It is allowed for `gateway` & executors.

<table>
<tr>
<td> <center><b>Before</b></center> </td> <td><b><center>After</center></b></td>
</tr>
<tr>
<td>

```yaml
jtype: Flow
jcloud:
  expose_gateway: false
executors:
  - name: custom1
    uses: jinahub+docker://CustomExecutor1
  - name: custom2
    uses: jinahub+docker://CustomExecutor2
```
</td>
<td>

```yaml
jtype: Flow
jcloud:
  gateway: 
    expose: false
executors:
  - name: custom1
    uses: jinahub+docker://CustomExecutor1
    jcloud:
       expose: true
  - name: custom2
    uses: jinahub+docker://CustomExecutor2
    jcloud:
       expose: true
```
</td>
</tr>
</table>

3. `gateway.kind` is removed (only Kong Ingress) is allowed.

## Changes to `jc` CLI

1. `--name` arg is removed from `jc deploy` arg list. To pass `name` to a Flow YAML, please use `jcloud.name` in the Flow YAML.

<table>
<tr>
<td> <center><b>Before</b></center> </td> <td><b><center>After</center></b></td>
</tr>
<tr>
<td>

```bash
jc deploy flow.yml --name my-flow-name
```
</td>
<td>

```yaml
jtype: Flow
jcloud:
   name: my-flow-name
executors:
  - ...
```
</td>
</tr>
</table>

2. Passing environment variables using `--env-file` is dropped. Users can use [`env` field in the Flow yaml](https://docs.jina.ai/envs/#environment-variables).

3. `jc deploy` / `jc remove` won't show any logs on CI anymore, rather redirect users to the Grafana dashboard. 

4. `--status` is renamed to `--phase` in `jc list` command.

4. `jc logs` command dropped.
